-- Generated by gold-es pipeline: dex_entries
return {
  ["MACHAMP"] = {
    ["text"] = "Mueve rápidamente<NEXT>sus cuatro brazos<NEXT>para golpear con",
    ["text2"] = "incesantes golpes<NEXT>y puñetazos desde<NEXT>todos los ángulos.",
  },
  ["DIGLETT"] = {
    ["text"] = "Su piel es muy<NEXT>fina. Si se expone<NEXT>a la luz, su",
    ["text2"] = "sangre se calienta<NEXT>y su crecimiento<NEXT>se debilita.",
  },
  ["HAUNTER"] = {
    ["text"] = "En la oscuridad<NEXT>total, donde no<NEXT>se ve nada,",
    ["text2"] = "HAUNTER acecha<NEXT>a su próxima<NEXT>víctima.",
  },
  ["PIDGEOTTO"] = {
    ["text"] = "Su visión es<NEXT>extraordinaria.<NEXT>Aunque vuele muy",
    ["text2"] = "alto, detectará<NEXT>todo movimiento<NEXT>de su presa.",
  },
  ["ARCANINE"] = {
    ["text"] = "Este POKéMON chino<NEXT>legendario es<NEXT>considerado",
    ["text2"] = "magnífico. A mucha<NEXT>gente le encanta<NEXT>su gran melena.",
  },
  ["CYNDAQUIL"] = {
    ["text"] = "Es tímido, y<NEXT>siempre se enrosca<NEXT>como una pelota.",
    ["text2"] = "Si es atacado,<NEXT>enciende su lomo<NEXT>para protegerse.",
  },
  ["DODUO"] = {
    ["text"] = "Alternando ambas<NEXT>cabezas arriba y<NEXT>abajo, se",
    ["text2"] = "equilibra para<NEXT>correr de una<NEXT>forma más estable.",
  },
  ["CROCONAW"] = {
    ["text"] = "Si pierde un<NEXT>colmillo, le<NEXT>crecerá otro en su",
    ["text2"] = "lugar. Siempre<NEXT>tiene 48 colmillos<NEXT>en su boca.",
  },
  ["HOPPIP"] = {
    ["text"] = "Para evitar ser<NEXT>llevados por el<NEXT>viento, se reúnen",
    ["text2"] = "en grupos, aunque<NEXT>adoran las suaves<NEXT>brisas.",
  },
  ["FERALIGATR"] = {
    ["text"] = "Al morder con sus<NEXT>feroces fauces,<NEXT>mueve su cabeza",
    ["text2"] = "despedazando<NEXT>salvajemente<NEXT>a su víctima.",
  },
  ["GIRAFARIG"] = {
    ["text"] = "Su cola tiene un<NEXT>pequeño cerebro.<NEXT>¡Cuidado!",
    ["text2"] = "Si te acercas,<NEXT>puede reaccionar a<NEXT>tu olor y morder.",
  },
  ["LEDYBA"] = {
    ["text"] = "Es muy tímido.<NEXT>Tiene miedo de<NEXT>moverse cuando va",
    ["text2"] = "solo. Pero si<NEXT>va en grupo, se<NEXT>vuelve muy activo.",
  },
  ["CHINCHOU"] = {
    ["text"] = "Descarga electri-<NEXT>cidad positiva y<NEXT>negativa entre las",
    ["text2"] = "puntas de sus dos<NEXT>antenas y electro-<NEXT>cuta al enemigo.",
  },
  ["GRANBULL"] = {
    ["text"] = "Es muy tímido<NEXT>y asustadizo.<NEXT>Si se siente",
    ["text2"] = "atacado, se moverá<NEXT>para evitar<NEXT>al enemigo.",
  },
  ["CHIKORITA"] = {
    ["text"] = "Un dulce aroma se<NEXT>desprende de la<NEXT>hoja de su cabeza.",
    ["text2"] = "Es dócil y le<NEXT>encanta absorber<NEXT>los rayos de sol.",
  },
  ["MR__MIME"] = {
    ["text"] = "Un hábil mimo<NEXT>desde que nace.<NEXT>Aprende a crear",
    ["text2"] = "objetos invisibles<NEXT>a medida que<NEXT>crece.",
  },
  ["ESPEON"] = {
    ["text"] = "Usa el corto<NEXT>pelaje que cubre<NEXT>su cuerpo para",
    ["text2"] = "sentir el viento<NEXT>y predecir las<NEXT>acciones enemigas.",
  },
  ["FLAAFFY"] = {
    ["text"] = "Como almacena<NEXT>tanta<NEXT>electricidad,",
    ["text2"] = "ha desarrollado<NEXT>parches donde no<NEXT>crece ni la lana.",
  },
  ["FLAREON"] = {
    ["text"] = "Almacena parte del<NEXT>aire que inhala en<NEXT>su bolsa interior,",
    ["text2"] = "que llega a<NEXT>calentarse a más<NEXT>de 1.700 grados.",
  },
  ["ELEKID"] = {
    ["text"] = "Gira sus brazos<NEXT>para generar<NEXT>electricidad, pero",
    ["text2"] = "se agota rápido,<NEXT>así que sólo se<NEXT>recarga un poco.",
  },
  ["FORRETRESS"] = {
    ["text"] = "Todo su cuerpo<NEXT>está protegido por<NEXT>una coraza de",
    ["text2"] = "metal. Lo que<NEXT>esconde la coraza<NEXT>es un misterio.",
  },
  ["PSYDUCK"] = {
    ["text"] = "Tiene poderes<NEXT>místicos que no<NEXT>recuerda haber",
    ["text2"] = "usado. Por eso,<NEXT>siempre parece<NEXT>desconcertado.",
  },
  ["CHARMELEON"] = {
    ["text"] = "Por naturaleza,<NEXT>se acalora con<NEXT>facilidad: siempre",
    ["text2"] = "está buscando<NEXT>enemigos. Sólo se<NEXT>calma cuando gana.",
  },
  ["GOLDEEN"] = {
    ["text"] = "Sus aletas dorsal,<NEXT>trasera y pectoral<NEXT>ondean gráciles en",
    ["text2"] = "el agua. Por eso<NEXT>es llamado el<NEXT>bailarín acuático.",
  },
  ["IGGLYBUFF"] = {
    ["text"] = "Su cuerpo es muy<NEXT>blando. Si se pone<NEXT>a rodar, rebotará",
    ["text2"] = "contra todo y<NEXT>será imposible<NEXT>de parar.",
  },
  ["TOGETIC"] = {
    ["text"] = "Dicen que aparece<NEXT>entre gentes<NEXT>cuidadosas y de",
    ["text2"] = "buen corazón, a<NEXT>quienes inunda<NEXT>de felicidad.",
  },
  ["TYPHLOSION"] = {
    ["text"] = "Si su furia crece,<NEXT>se calienta tanto<NEXT>que cualquier cosa",
    ["text2"] = "que toque se<NEXT>prenderá al<NEXT>instante.",
  },
  ["BLASTOISE"] = {
    ["text"] = "Deliberadamente se<NEXT>hace más pesado<NEXT>para contrarrestar",
    ["text2"] = "la fuerza de los<NEXT>chorros de agua<NEXT>que dispara.",
  },
  ["ABRA"] = {
    ["text"] = "Siente los ataques<NEXT>inminentes y se<NEXT>TELETRANSPORTA a",
    ["text2"] = "un lugar seguro,<NEXT>antes de que éstos<NEXT>puedan darle.",
  },
  ["ONIX"] = {
    ["text"] = "Gira y se retuerce<NEXT>bajo la tierra.<NEXT>El atronador",
    ["text2"] = "rugido de su<NEXT>excavación resuena<NEXT>a lo lejos.",
  },
  ["URSARING"] = {
    ["text"] = "Aunque trepa<NEXT>muy bien,<NEXT>prefiere agitar",
    ["text2"] = "los árboles con<NEXT>sus patas y comer<NEXT>las BAYAS caídas.",
  },
  ["DUNSPARCE"] = {
    ["text"] = "Este POKéMON<NEXT>escapa hacia<NEXT>atrás perforando",
    ["text2"] = "el suelo con<NEXT>su cola, si es<NEXT>descubierto.",
  },
  ["BLISSEY"] = {
    ["text"] = "Cualquiera que<NEXT>pruebe un poco de<NEXT>huevo de BLISSEY,",
    ["text2"] = "se volverá más<NEXT>amable y agradable<NEXT>con todos.",
  },
  ["TENTACRUEL"] = {
    ["text"] = "Sus 80 tentáculos<NEXT>absorben agua y<NEXT>se alargan para",
    ["text2"] = "OPRIMIR la<NEXT>respiración de sus<NEXT>presas y enemigos.",
  },
  ["STARYU"] = {
    ["text"] = "De noche, la parte<NEXT>central de su<NEXT>cuerpo parpadea",
    ["text2"] = "al ritmo del<NEXT>latido cardíaco<NEXT>de los humanos.",
  },
  ["SNEASEL"] = {
    ["text"] = "Sus ocultas garras<NEXT>son muy afiladas.<NEXT>Si le atacan,",
    ["text2"] = "extiende sus<NEXT>garras y asusta<NEXT>al enemigo.",
  },
  ["GRAVELER"] = {
    ["text"] = "De naturaleza<NEXT>descuidada y<NEXT>libre, no le",
    ["text2"] = "importa dañarse<NEXT>cuando baja<NEXT>rodando montañas.",
  },
  ["GROWLITHE"] = {
    ["text"] = "De naturaleza<NEXT>valiente y<NEXT>honrada, se",
    ["text2"] = "enfrenta sin miedo<NEXT>a enemigos más<NEXT>grandes y fuertes.",
  },
  ["BAYLEEF"] = {
    ["text"] = "Su cuello huele<NEXT>a especias. Dicen<NEXT>que por alguna",
    ["text2"] = "razón, su simple<NEXT>olor te incita<NEXT>a luchar.",
  },
  ["SLOWPOKE"] = {
    ["text"] = "Descansa ocioso<NEXT>junto al agua.<NEXT>Si algo muerde",
    ["text2"] = "su cola, no lo<NEXT>notará en todo<NEXT>el día.",
  },
  ["LAPRAS"] = {
    ["text"] = "Son buenos de<NEXT>corazón. Muchos<NEXT>fueron capturados",
    ["text2"] = "por ser tan<NEXT>pacíficos. Ahora<NEXT>hay muchos menos.",
  },
  ["ELECTABUZZ"] = {
    ["text"] = "Por la superficie<NEXT>de su piel corre<NEXT>la electricidad.",
    ["text2"] = "En la oscuridad,<NEXT>su cuerpo se torna<NEXT>blanquecino.",
  },
  ["VOLTORB"] = {
    ["text"] = "Se mueve rodando.<NEXT>Si el terreno es<NEXT>irregular, una",
    ["text2"] = "chispa provocada<NEXT>por algún bache<NEXT>lo haría explotar.",
  },
  ["TEDDIURSA"] = {
    ["text"] = "Si encuentra miel,<NEXT>brillará la marca<NEXT>de su frente.",
    ["text2"] = "Se lame las garras<NEXT>cuando están<NEXT>llenas de miel.",
  },
  ["ARTICUNO"] = {
    ["text"] = "Dicen que las<NEXT>magníficas alas<NEXT>translúcidas de",
    ["text2"] = "este legendario<NEXT>pájaro POKéMON<NEXT>son de hielo.",
  },
  ["ARIADOS"] = {
    ["text"] = "Teje su telaraña<NEXT>desde atrás y<NEXT>desde su boca.",
    ["text2"] = "Es muy difícil<NEXT>saber dónde<NEXT>está cada cual.",
  },
  ["CHANSEY"] = {
    ["text"] = "Camina con cuidado<NEXT>para que no se<NEXT>rompa su huevo.",
    ["text2"] = "Sin embargo, es<NEXT>extremadamente<NEXT>rápido escapando.",
  },
  ["BELLSPROUT"] = {
    ["text"] = "Aunque su cuerpo<NEXT>es extremadamente<NEXT>delgado, es muy",
    ["text2"] = "rápido a la hora<NEXT>de capturar a<NEXT>sus presas.",
  },
  ["CLEFAIRY"] = {
    ["text"] = "La luz de luna<NEXT>que guarda en las<NEXT>alas de su lomo",
    ["text2"] = "parece darle<NEXT>la habilidad de<NEXT>flotar en el aire.",
  },
  ["HORSEA"] = {
    ["text"] = "Si es atacado por<NEXT>un enemigo más<NEXT>grande, nada veloz",
    ["text2"] = "a un lugar seguro<NEXT>gracias a su<NEXT>aleta dorsal.",
  },
  ["TYRANITAR"] = {
    ["text"] = "Su cuerpo es casi<NEXT>inmune a los<NEXT>ataques. Por eso",
    ["text2"] = "le encanta<NEXT>desafiar a<NEXT>sus enemigos.",
  },
  ["HOOTHOOT"] = {
    ["text"] = "Camina con un<NEXT>solo pie.<NEXT>Cambia tan",
    ["text2"] = "rápidamente de<NEXT>pie que apenas<NEXT>se le ve.",
  },
  ["SUICUNE"] = {
    ["text"] = "Conocido como la<NEXT>reencarnación de<NEXT>los vientos del",
    ["text2"] = "norte, puede<NEXT>purificar aguas<NEXT>turbias y sucias.",
  },
  ["CHARMANDER"] = {
    ["text"] = "La llama de su<NEXT>cola indica su<NEXT>fuerza vital.",
    ["text2"] = "Si está débil,<NEXT>la llama arderá<NEXT>más tenue.",
  },
  ["GOLDUCK"] = {
    ["text"] = "Cuando nada a toda<NEXT>velocidad usando<NEXT>sus palmeadas",
    ["text2"] = "extremidades,<NEXT>su frente comienza<NEXT>a brillar.",
  },
  ["LEDIAN"] = {
    ["text"] = "Cuando parpadean<NEXT>las estrellas en<NEXT>el cielo nocturno,",
    ["text2"] = "se mece,<NEXT>desprendiendo un<NEXT>polvo brillante.",
  },
  ["NATU"] = {
    ["text"] = "Va dando saltitos<NEXT>porque sus alas no<NEXT>han crecido lo",
    ["text2"] = "suficiente.<NEXT>Siempre está<NEXT>pendiente de algo.",
  },
  ["JYNX"] = {
    ["text"] = "Mueve su cuerpo<NEXT>rítmicamente.<NEXT>Parece cambiar de",
    ["text2"] = "ritmo dependiendo<NEXT>de cómo se<NEXT>sienta.",
  },
  ["CATERPIE"] = {
    ["text"] = "Para protegerse<NEXT>despide un hedor<NEXT>horrible de sus",
    ["text2"] = "antenas, con el<NEXT>que repele a<NEXT>sus enemigos.",
  },
  ["BUTTERFREE"] = {
    ["text"] = "Recoge miel a<NEXT>diario y la<NEXT>adhiere al pelo",
    ["text2"] = "de sus patas<NEXT>para llevarla<NEXT>a su colmena.",
  },
  ["HYPNO"] = {
    ["text"] = "Cuando está muy<NEXT>hambriento, duerme<NEXT>a los humanos que",
    ["text2"] = "encuentra para<NEXT>poder devorar<NEXT>sus sueños.",
  },
  ["DEWGONG"] = {
    ["text"] = "Su aerodinámico<NEXT>cuerpo avanza<NEXT>fácilmente por el",
    ["text2"] = "agua. Cuanto más<NEXT>fría, más<NEXT>diversión.",
  },
  ["STARMIE"] = {
    ["text"] = "La parte central<NEXT>de su cuerpo se<NEXT>denomina núcleo.",
    ["text2"] = "Brilla en colores<NEXT>diferentes cada<NEXT>vez que es visto.",
  },
  ["SUNKERN"] = {
    ["text"] = "Puede caer del<NEXT>cielo de repente.<NEXT>Si le ataca un",
    ["text2"] = "SPEAROW, moverá<NEXT>violentamente<NEXT>sus hojas.",
  },
  ["HO_OH"] = {
    ["text"] = "Cuenta la leyenda<NEXT>que este POKéMON<NEXT>vuela por el",
    ["text2"] = "cielo con sus<NEXT>magníficas alas<NEXT>de siete colores.",
  },
  ["PIDGEOT"] = {
    ["text"] = "Sus músculos<NEXT>pectorales son<NEXT>tan fuertes que",
    ["text2"] = "podría parar una<NEXT>ventisca con unos<NEXT>cuantos aleteos.",
  },
  ["RAIKOU"] = {
    ["text"] = "Las nubes de<NEXT>lluvia que lleva<NEXT>le permiten lanzar",
    ["text2"] = "rayos a voluntad.<NEXT>Dicen que apareció<NEXT>con un rayo.",
  },
  ["KINGDRA"] = {
    ["text"] = "Dicen que suele<NEXT>esconderse en<NEXT>cuevas submarinas.",
    ["text2"] = "Puede crear<NEXT>torbellinos al<NEXT>bostezar.",
  },
  ["GRIMER"] = {
    ["text"] = "Mientras se mueve,<NEXT>pierde partes<NEXT>de su cuerpo, de",
    ["text2"] = "donde saldrá un<NEXT>nuevo GRIMER. Esto<NEXT>aumenta su hedor.",
  },
  ["SLUGMA"] = {
    ["text"] = "No duerme nunca.<NEXT>Tiene que seguir<NEXT>moviéndose porque",
    ["text2"] = "si se detiene,<NEXT>su cuerpo de lava<NEXT>podría enfriarse.",
  },
  ["MEW"] = {
    ["text"] = "Dicen que sólo se<NEXT>aparece a los<NEXT>puros de corazón,",
    ["text2"] = "y a quienes desean<NEXT>verlo con todas<NEXT>sus fuerzas.",
  },
  ["GLOOM"] = {
    ["text"] = "Lo que parece ser<NEXT>baba es realmente<NEXT>miel. Es muy",
    ["text2"] = "pegajoso y se<NEXT>adhiere tercamente<NEXT>si lo tocas.",
  },
  ["SKIPLOOM"] = {
    ["text"] = "La flor de<NEXT>su cabeza se<NEXT>abre y cierra",
    ["text2"] = "según suba o<NEXT>baje la<NEXT>temperatura.",
  },
  ["KRABBY"] = {
    ["text"] = "Ante el peligro,<NEXT>se camufla con<NEXT>las burbujas",
    ["text2"] = "que desprende su<NEXT>boca, para parecer<NEXT>más grande.",
  },
  ["JOLTEON"] = {
    ["text"] = "Concentra la<NEXT>débil actividad<NEXT>eléctrica de sus",
    ["text2"] = "células para<NEXT>lanzar dañinas<NEXT>descargas.",
  },
  ["KADABRA"] = {
    ["text"] = "Es muy fuerte<NEXT>espiritualmente.<NEXT>Cuanto mayor sea",
    ["text2"] = "el peligro,<NEXT>mayor será su<NEXT>poder psíquico.",
  },
  ["HERACROSS"] = {
    ["text"] = "Este fuerte<NEXT>POKéMON clava su<NEXT>preciado cuerno",
    ["text2"] = "en la tripa del<NEXT>enemigo, lo eleva<NEXT>y luego lo arroja.",
  },
  ["WEEZING"] = {
    ["text"] = "Si uno de los<NEXT>gemelos KOFFING se<NEXT>infla, el otro se",
    ["text2"] = "desinfla. Mezclan<NEXT>constantemente sus<NEXT>venenosos gases.",
  },
  ["MURKROW"] = {
    ["text"] = "Temido y odiado<NEXT>por muchos, dicen<NEXT>que trae la",
    ["text2"] = "desgracia a todos<NEXT>aquéllos que lo<NEXT>ven por la noche.",
  },
  ["FARFETCH_D"] = {
    ["text"] = "Si a alguien se le<NEXT>ocurre estropear<NEXT>los cultivos de",
    ["text2"] = "puerros, usará<NEXT>su propio puerro<NEXT>para evitarlo.",
  },
  ["OMANYTE"] = {
    ["text"] = "Resucitado de un<NEXT>fósil, este<NEXT>POKéMON usa el",
    ["text2"] = "aire de su concha<NEXT>para sumergirse<NEXT>y emerger.",
  },
  ["SEEL"] = {
    ["text"] = "Aunque torpe en<NEXT>tierra, es un<NEXT>hábil nadador.",
    ["text2"] = "Lo que más le<NEXT>gusta es nadar<NEXT>en mares helados.",
  },
  ["IVYSAUR"] = {
    ["text"] = "Puede aumentar su<NEXT>fuerza con energía<NEXT>solar. Ésta",
    ["text2"] = "también hace que<NEXT>crezca el capullo<NEXT>de su lomo.",
  },
  ["SCYTHER"] = {
    ["text"] = "Avanza por la<NEXT>hierba con sus<NEXT>afiladas guadañas,",
    ["text2"] = "más rápido de lo<NEXT>que el ojo humano<NEXT>pueda percibir.",
  },
  ["LUGIA"] = {
    ["text"] = "Dicen que<NEXT>permanece en<NEXT>silencio en el",
    ["text2"] = "fondo del mar<NEXT>debido a su<NEXT>inmenso poder.",
  },
  ["MARILL"] = {
    ["text"] = "La punta de<NEXT>su cola, que<NEXT>contiene aceite,",
    ["text2"] = "le permite nadar<NEXT>sin miedo a<NEXT>ahogarse.",
  },
  ["NIDORINA"] = {
    ["text"] = "Cuando alimenta a<NEXT>sus crías, primero<NEXT>mastica y ablanda",
    ["text2"] = "la comida y luego<NEXT>la escupe para<NEXT>su prole.",
  },
  ["BELLOSSOM"] = {
    ["text"] = "Los BELLOSSOM<NEXT>suelen reunirse<NEXT>para bailar. Dicen",
    ["text2"] = "que sus danzas son<NEXT>un ritual para<NEXT>invocar al sol.",
  },
  ["HITMONCHAN"] = {
    ["text"] = "Sus puños cortan<NEXT>el aire, aunque<NEXT>parece necesitar",
    ["text2"] = "un descanso tras<NEXT>3 minutos de<NEXT>combate.",
  },
  ["POLIWRATH"] = {
    ["text"] = "Este fuerte<NEXT>y hábil nadador<NEXT>es capaz hasta",
    ["text2"] = "de cruzar los<NEXT>grandes océanos,<NEXT>sólo por placer.",
  },
  ["SNORLAX"] = {
    ["text"] = "Su supuesto grito<NEXT>podrían ser<NEXT>sus ronquidos,",
    ["text2"] = "o los ruidos de<NEXT>su hambrienta<NEXT>tripa.",
  },
  ["GYARADOS"] = {
    ["text"] = "Dicen que en<NEXT>guerras pasadas,<NEXT>GYARADOS aparecía",
    ["text2"] = "dejando a su<NEXT>paso la ruina<NEXT>y el caos.",
  },
  ["PORYGON2"] = {
    ["text"] = "Esta versión<NEXT>mejorada de<NEXT>PORYGON fue creada",
    ["text2"] = "para explorar el<NEXT>espacio, aunque<NEXT>no puede volar.",
  },
  ["PERSIAN"] = {
    ["text"] = "Muy valorado<NEXT>por su aire<NEXT>sofisticado. Sin",
    ["text2"] = "embargo, ataca y<NEXT>araña por el más<NEXT>mínimo motivo.",
  },
  ["POLIWHIRL"] = {
    ["text"] = "La espiral de su<NEXT>pecho se ondula<NEXT>delicadamente.",
    ["text2"] = "Mirarlo provoca<NEXT>gradualmente un<NEXT>estado de sopor.",
  },
  ["SEAKING"] = {
    ["text"] = "Durante la puesta<NEXT>acuden SEAKING de<NEXT>todas partes,",
    ["text2"] = "coloreando los<NEXT>ríos de un<NEXT>rojo brillante.",
  },
  ["TYROGUE"] = {
    ["text"] = "Ataca siempre con<NEXT>mucha energía.<NEXT>Para fortalecerse",
    ["text2"] = "a sí mismo, sigue<NEXT>luchando aunque<NEXT>pierda.",
  },
  ["HOUNDOOM"] = {
    ["text"] = "Si te quemas con<NEXT>las llamas que<NEXT>lanza por su",
    ["text2"] = "boca, el dolor<NEXT>no desaparecerá<NEXT>nunca.",
  },
  ["MAGBY"] = {
    ["text"] = "Cada vez que<NEXT>inspira y expira,<NEXT>lanza ascuas",
    ["text2"] = "por su boca y<NEXT>por sus fosas<NEXT>nasales.",
  },
  ["WARTORTLE"] = {
    ["text"] = "Es reconocido<NEXT>como símbolo de<NEXT>longevidad. Los",
    ["text2"] = "WARTORTLE ancianos<NEXT>tienen algas sobre<NEXT>el caparazón.",
  },
  ["MAROWAK"] = {
    ["text"] = "Se le ha visto<NEXT>golpeando rocas<NEXT>con el hueso",
    ["text2"] = "que lleva, para<NEXT>enviar mensajes<NEXT>a los demás.",
  },
  ["HITMONTOP"] = {
    ["text"] = "Si te gustan sus<NEXT>suaves, elegantes<NEXT>y danzarinas",
    ["text2"] = "patadas,<NEXT>acabarás<NEXT>taladrado.",
  },
  ["ELECTRODE"] = {
    ["text"] = "Es peligroso. Si<NEXT>almacena mucha<NEXT>electricidad y",
    ["text2"] = "está ocioso,<NEXT>se entretiene<NEXT>explosionando.",
  },
  ["MAGNETON"] = {
    ["text"] = "Tres MAGNEMITE se<NEXT>enlazan por una<NEXT>intensa fuerza",
    ["text2"] = "magnética. Si te<NEXT>acercas, te<NEXT>dolerán los oídos.",
  },
  ["CHARIZARD"] = {
    ["text"] = "Si CHARIZARD se<NEXT>enfurece, la llama<NEXT>de la punta de su",
    ["text2"] = "cola producirá<NEXT>destellos de<NEXT>color azul claro.",
  },
  ["BULBASAUR"] = {
    ["text"] = "La semilla de su<NEXT>lomo está llena<NEXT>de nutrientes.",
    ["text2"] = "La semilla brota<NEXT>a medida que el<NEXT>POKéMON crece.",
  },
  ["KABUTO"] = {
    ["text"] = "En raras ocasiones<NEXT>se han encontrado<NEXT>como fósiles,",
    ["text2"] = "porque se habían<NEXT>escondido en el<NEXT>fondo marino.",
  },
  ["BEEDRILL"] = {
    ["text"] = "Puede vencer a<NEXT>cualquier rival<NEXT>con sus potentes",
    ["text2"] = "aguijones<NEXT>venenosos. Puede<NEXT>atacar en grupo.",
  },
  ["LICKITUNG"] = {
    ["text"] = "Los nervios súper-<NEXT>desarrollados<NEXT>hallados por toda",
    ["text2"] = "su lengua permiten<NEXT>que la manipule<NEXT>hábilmente.",
  },
  ["PONYTA"] = {
    ["text"] = "Al nacer es un<NEXT>poco lento, pero<NEXT>poco a poco se",
    ["text2"] = "vuelve más rápido<NEXT>para poder seguir<NEXT>a sus padres.",
  },
  ["SLOWKING"] = {
    ["text"] = "Su intelecto e<NEXT>intuición son<NEXT>increíbles.",
    ["text2"] = "No pierde la<NEXT>compostura en<NEXT>ninguna situación.",
  },
  ["PUPITAR"] = {
    ["text"] = "Su caparazón es<NEXT>duro como una<NEXT>piedra, y muy",
    ["text2"] = "resistente.<NEXT>Su GOLPE puede<NEXT>derribar montañas.",
  },
  ["PARASECT"] = {
    ["text"] = "Suele vivir en<NEXT>lugares oscuros<NEXT>y húmedos, los",
    ["text2"] = "preferidos, no del<NEXT>bicho, sino de la<NEXT>seta de su lomo.",
  },
  ["MAREEP"] = {
    ["text"] = "Cuando almacena<NEXT>electricidad en<NEXT>su cuerpo, dobla",
    ["text2"] = "su volumen.<NEXT>Tócalo y recibirás<NEXT>una descarga.",
  },
  ["KABUTOPS"] = {
    ["text"] = "Repliega sus<NEXT>extremidades en el<NEXT>agua para hacerse",
    ["text2"] = "más compacto, y<NEXT>mueve su concha<NEXT>para nadar rápido.",
  },
  ["MAGMAR"] = {
    ["text"] = "Odia los lugares<NEXT>fríos, y despide<NEXT>calientes llamas",
    ["text2"] = "para hacer el<NEXT>entorno un poco<NEXT>más confortable.",
  },
  ["JIGGLYPUFF"] = {
    ["text"] = "Si se hincha para<NEXT>CANTAR una nana,<NEXT>cantará más",
    ["text2"] = "tiempo, y puede<NEXT>causar sopor<NEXT>en el público.",
  },
  ["DRATINI"] = {
    ["text"] = "Al nacer ya<NEXT>tiene un tamaño<NEXT>considerable. Muda",
    ["text2"] = "continuamente de<NEXT>piel a la vez<NEXT>que crece.",
  },
  ["MISDREAVUS"] = {
    ["text"] = "Le gusta hacer<NEXT>travesuras como<NEXT>gritar y aullar",
    ["text2"] = "por la noche,<NEXT>para asustar<NEXT>a la gente.",
  },
  ["WOBBUFFET"] = {
    ["text"] = "Odia la luz y las<NEXT>sacudidas. Si le<NEXT>atacan, infla su",
    ["text2"] = "cuerpo para<NEXT>aumentar su con-<NEXT>traataque.",
  },
  ["PIDGEY"] = {
    ["text"] = "Suele ocultarse<NEXT>entre altas<NEXT>hierbas. Como no",
    ["text2"] = "le gusta luchar,<NEXT>se defiende<NEXT>pateando arena.",
  },
  ["KOFFING"] = {
    ["text"] = "Su fino y delgado<NEXT>cuerpo está lleno<NEXT>de gases que",
    ["text2"] = "causan tos, estor-<NEXT>nudos y lagrimeos<NEXT>constantes.",
  },
  ["MUK"] = {
    ["text"] = "Les encanta<NEXT>reunirse en zonas<NEXT>apestosas donde se",
    ["text2"] = "acumula el lodo,<NEXT>haciendo su olor<NEXT>más insoportable.",
  },
  ["VAPOREON"] = {
    ["text"] = "Cuando las aletas<NEXT>de VAPOREON<NEXT>vibran, significa",
    ["text2"] = "que lloverá en<NEXT>las próximas<NEXT>horas.",
  },
  ["DELIBIRD"] = {
    ["text"] = "Siempre lleva<NEXT>comida. Dicen<NEXT>que hay muchos",
    ["text2"] = "desaparecidos que<NEXT>sobrevivieron<NEXT>gracias a ésta.",
  },
  ["TENTACOOL"] = {
    ["text"] = "Cuando baja la<NEXT>marea, podrían<NEXT>aparecer restos",
    ["text2"] = "deshidratados de<NEXT>TENTACOOL junto<NEXT>a la orilla.",
  },
  ["SPINARAK"] = {
    ["text"] = "Mantiene la misma<NEXT>postura en su<NEXT>telaraña durante",
    ["text2"] = "días, esperando a<NEXT>que se acerque una<NEXT>presa inocente.",
  },
  ["TAUROS"] = {
    ["text"] = "Luchan entre sí<NEXT>con sus cuernos.<NEXT>El jefe de la",
    ["text2"] = "manada alardea de<NEXT>las cicatrices<NEXT>de sus cuernos.",
  },
  ["RATTATA"] = {
    ["text"] = "Come de todo. Se<NEXT>establece donde<NEXT>quiera que haya",
    ["text2"] = "comida, y se<NEXT>reproduce<NEXT>continuamente.",
  },
  ["RATICATE"] = {
    ["text"] = "Roe cualquier cosa<NEXT>con sus duros<NEXT>colmillos. Puede",
    ["text2"] = "hasta derribar<NEXT>ciertos edificios<NEXT>royéndolos.",
  },
  ["EKANS"] = {
    ["text"] = "Puede separar su<NEXT>mandíbula para<NEXT>engullir a grandes",
    ["text2"] = "presas, aunque<NEXT>esto le dificulte<NEXT>el movimiento.",
  },
  ["ZAPDOS"] = {
    ["text"] = "Este legendario<NEXT>pájaro POKéMON<NEXT>provoca violentas",
    ["text2"] = "tormentas de rayos<NEXT>agitando sus<NEXT>brillantes alas.",
  },
  ["MAGCARGO"] = {
    ["text"] = "La concha de su<NEXT>lomo son restos<NEXT>de piel enfriada y",
    ["text2"] = "endurecida. Se<NEXT>rompe fácilmente<NEXT>con sólo tocarla.",
  },
  ["PIKACHU"] = {
    ["text"] = "Este inteligente<NEXT>POKéMON tuesta<NEXT>las duras BAYAS",
    ["text2"] = "con electricidad<NEXT>para hacerlas<NEXT>más comestibles.",
  },
  ["EEVEE"] = {
    ["text"] = "Es capaz de<NEXT>alterar la<NEXT>composición de",
    ["text2"] = "su cuerpo para<NEXT>confundirse con<NEXT>el entorno.",
  },
  ["CROBAT"] = {
    ["text"] = "Es tan silencioso<NEXT>cuando vuela en la<NEXT>oscuridad con sus",
    ["text2"] = "cuatro alas, que<NEXT>cuesta percibirlo<NEXT>cuando se acerca.",
  },
  ["MANKEY"] = {
    ["text"] = "Tiene muy mal<NEXT>humor. Cuando<NEXT>se agrupan atacan",
    ["text2"] = "a cualquier cosa<NEXT>sin motivo<NEXT>aparente.",
  },
  ["NIDOKING"] = {
    ["text"] = "Mueve su cola<NEXT>en combate. Si<NEXT>su enemigo queda",
    ["text2"] = "atontado, le<NEXT>embiste con su<NEXT>robusto cuerpo.",
  },
  ["GENGAR"] = {
    ["text"] = "Roba el calor de<NEXT>sus alrededores.<NEXT>Si sientes un",
    ["text2"] = "escalofrío, seguro<NEXT>que hay algún<NEXT>GENGAR cerca.",
  },
  ["MAGIKARP"] = {
    ["text"] = "Un POKéMON<NEXT>desvalido y<NEXT>patético. A veces",
    ["text2"] = "es capaz de saltar<NEXT>alto, pero nunca<NEXT>más de 2 metros.",
  },
  ["EXEGGCUTE"] = {
    ["text"] = "Su cáscara es muy<NEXT>resistente. Si<NEXT>llega a romperse,",
    ["text2"] = "podría sobrevivir<NEXT>si evita derramar<NEXT>su contenido.",
  },
  ["AIPOM"] = {
    ["text"] = "Su cola es tan<NEXT>potente que puede<NEXT>usarla para",
    ["text2"] = "agarrarse a la<NEXT>rama de un árbol<NEXT>y no caer.",
  },
  ["NIDORAN_M"] = {
    ["text"] = "Es pequeño, pero<NEXT>su cuerno está<NEXT>lleno de veneno.",
    ["text2"] = "Primero embiste, y<NEXT>después lanza su<NEXT>venenosa cornada.",
  },
  ["SLOWBRO"] = {
    ["text"] = "Si el SHELLDER que<NEXT>muerde su cola se<NEXT>desprende durante",
    ["text2"] = "una lucha, se<NEXT>convertirá en un<NEXT>simple SLOWPOKE.",
  },
  ["STANTLER"] = {
    ["text"] = "Su cornamenta<NEXT>cambia el flujo<NEXT>del aire para",
    ["text2"] = "crear un espacio<NEXT>de realidad<NEXT>distorsionada.",
  },
  ["NIDOQUEEN"] = {
    ["text"] = "Su cuerpo está<NEXT>cubierto por<NEXT>pequeñas escamas.",
    ["text2"] = "Nunca parece<NEXT>acobardarse ante<NEXT>ningún ataque.",
  },
  ["MEOWTH"] = {
    ["text"] = "Le fascinan los<NEXT>objetos redondos.<NEXT>No deja de jugar",
    ["text2"] = "con ellos hasta<NEXT>que se cansa<NEXT>y cae rendido.",
  },
  ["NIDORAN_F"] = {
    ["text"] = "El veneno oculto<NEXT>en su pequeño<NEXT>cuerno es",
    ["text2"] = "extremadamente<NEXT>potente. El menor<NEXT>roce sería fatal.",
  },
  ["DONPHAN"] = {
    ["text"] = "Tiene afilados y<NEXT>duros colmillos, y<NEXT>una gruesa piel.",
    ["text2"] = "Su PLACAJE es tan<NEXT>fuerte que puede<NEXT>derribar una casa.",
  },
  ["NINETALES"] = {
    ["text"] = "Cuentan algunas<NEXT>leyendas que cada<NEXT>una de sus nueve",
    ["text2"] = "colas posee su<NEXT>propio y único<NEXT>poder místico.",
  },
  ["AZUMARILL"] = {
    ["text"] = "Guardando silencio<NEXT>y prestando mucha<NEXT>atención puede",
    ["text2"] = "saber lo que hay<NEXT>en los rápidos<NEXT>y salvajes ríos.",
  },
  ["NOCTOWL"] = {
    ["text"] = "Sus ojos están<NEXT>especialmente<NEXT>adaptados,",
    ["text2"] = "concentrando la<NEXT>luz para poder ver<NEXT>en la oscuridad.",
  },
  ["SANDSLASH"] = {
    ["text"] = "En un intento por<NEXT>esconderse, saldrá<NEXT>corriendo a gran",
    ["text2"] = "velocidad, dejando<NEXT>tras de sí una<NEXT>gran polvareda.",
  },
  ["DRAGONAIR"] = {
    ["text"] = "Dicen que<NEXT>cuando su cuerpo<NEXT>desprende un aura,",
    ["text2"] = "el tiempo empieza<NEXT>a cambiar<NEXT>inmediatamente.",
  },
  ["WEEPINBELL"] = {
    ["text"] = "Aunque está lleno<NEXT>de ÁCIDO, no llega<NEXT>a derretirse",
    ["text2"] = "porque también<NEXT>rezuma fluidos<NEXT>neutralizantes.",
  },
  ["PINSIR"] = {
    ["text"] = "Cava guaridas con<NEXT>sus cuernos para<NEXT>pasar la noche.",
    ["text2"] = "Por la mañana, la<NEXT>tierra húmeda se<NEXT>pega a su cuerpo.",
  },
  ["FURRET"] = {
    ["text"] = "Construye un nido<NEXT>donde introducir<NEXT>su largo y delgado",
    ["text2"] = "cuerpo, en el que<NEXT>no pueden entrar<NEXT>otros POKéMON.",
  },
  ["ODDISH"] = {
    ["text"] = "Despertado por la<NEXT>luz de la luna,<NEXT>vaga por la noche.",
    ["text2"] = "De día se mantiene<NEXT>en silencio bajo<NEXT>la tierra.",
  },
  ["ENTEI"] = {
    ["text"] = "Cuando ladra, los<NEXT>volcanes entran<NEXT>en erupción. Como",
    ["text2"] = "no puede controlar<NEXT>su poder, corre<NEXT>siempre en cabeza.",
  },
  ["PRIMEAPE"] = {
    ["text"] = "Si te acercas a él<NEXT>mientras duerme,<NEXT>se despertará y te",
    ["text2"] = "dará caza en<NEXT>estado medio<NEXT>sonámbulo.",
  },
  ["PINECO"] = {
    ["text"] = "Le gusta engrosar<NEXT>su coraza<NEXT>añadiendo cortezas",
    ["text2"] = "de árbol. El<NEXT>aumento de peso<NEXT>no le molesta.",
  },
  ["OMASTAR"] = {
    ["text"] = "Al parecer, rompió<NEXT>la concha de<NEXT>SHELLDER con sus",
    ["text2"] = "afilados colmillos<NEXT>y absorbió el<NEXT>interior.",
  },
  ["WIGGLYTUFF"] = {
    ["text"] = "Su piel es tan<NEXT>suave que si dos<NEXT>de ellos se",
    ["text2"] = "acurrucan juntos,<NEXT>no querrán<NEXT>separarse nunca.",
  },
  ["RHYHORN"] = {
    ["text"] = "Es un poco torpe<NEXT>al girar debido a<NEXT>sus cuatro cortas",
    ["text2"] = "patas. Sólo puede<NEXT>atacar y correr en<NEXT>una dirección.",
  },
  ["RHYDON"] = {
    ["text"] = "Su dura coraza<NEXT>le protege hasta<NEXT>del calor de la",
    ["text2"] = "lava. Sin embargo,<NEXT>la coraza le<NEXT>hace insensible.",
  },
  ["FEAROW"] = {
    ["text"] = "Asciende al cielo<NEXT>repentinamente<NEXT>para caer después",
    ["text2"] = "en picado, y de un<NEXT>solo golpe atrapar<NEXT>a su presa.",
  },
  ["PARAS"] = {
    ["text"] = "Está cubierto de<NEXT>esporas de seta<NEXT>al nacer. A medida",
    ["text2"] = "que crece, las<NEXT>setas brotan<NEXT>de su lomo.",
  },
  ["CUBONE"] = {
    ["text"] = "Si está triste o<NEXT>solitario, agita<NEXT>la calavera y",
    ["text2"] = "emite un sonido<NEXT>lúgubre y<NEXT>lastimero.",
  },
  ["SUDOWOODO"] = {
    ["text"] = "Aunque pretende<NEXT>ser un árbol, en<NEXT>su composición se",
    ["text2"] = "parece más a<NEXT>una roca que<NEXT>a una planta.",
  },
  ["POLITOED"] = {
    ["text"] = "Si POLIWAG y<NEXT>POLIWHIRL oyen su<NEXT>grito, responderán",
    ["text2"] = "reuniéndose a lo<NEXT>largo y ancho<NEXT>de este mundo.",
  },
  ["DRAGONITE"] = {
    ["text"] = "Dicen que este<NEXT>POKéMON vuela<NEXT>continuamente por",
    ["text2"] = "la inmensidad del<NEXT>mar, y que rescata<NEXT>a los ahogados.",
  },
  ["GASTLY"] = {
    ["text"] = "Con su cuerpo<NEXT>gaseoso puede<NEXT>colarse por donde",
    ["text2"] = "quiera, aunque con<NEXT>un golpe de viento<NEXT>saldría despedido.",
  },
  ["RAPIDASH"] = {
    ["text"] = "Al galope,<NEXT>sus cuatro<NEXT>cascos apenas",
    ["text2"] = "tocan el suelo<NEXT>porque se mueve<NEXT>rapidísimo.",
  },
  ["SENTRET"] = {
    ["text"] = "Un POKéMON muy<NEXT>precavido. Se<NEXT>levanta con su",
    ["text2"] = "cola para tener<NEXT>una mejor vista de<NEXT>los alrededores.",
  },
  ["MEWTWO"] = {
    ["text"] = "Debido a sus<NEXT>increíbles<NEXT>capacidades de",
    ["text2"] = "lucha, sólo piensa<NEXT>en eliminar a<NEXT>sus enemigos.",
  },
  ["PHANPY"] = {
    ["text"] = "Mueve su larga<NEXT>trompa para jugar,<NEXT>pero como es tan",
    ["text2"] = "fuerte, esto<NEXT>podría resultar<NEXT>peligroso.",
  },
  ["SKARMORY"] = {
    ["text"] = "Sus fuertes alas<NEXT>parecen pesadas,<NEXT>aunque son",
    ["text2"] = "huecas y ligeras,<NEXT>y le permiten<NEXT>volar libremente.",
  },
  ["DITTO"] = {
    ["text"] = "Se puede<NEXT>transformar en<NEXT>cualquier cosa.",
    ["text2"] = "Cuando duerme, se<NEXT>vuelve roca para<NEXT>evitar el ataque.",
  },
  ["MAGNEMITE"] = {
    ["text"] = "Atraído por ondas<NEXT>electromagnéticas,<NEXT>podría acercarse",
    ["text2"] = "a los entrenadores<NEXT>que estén usando<NEXT>el POKéGEAR.",
  },
  ["STEELIX"] = {
    ["text"] = "Su cuerpo ha sido<NEXT>comprimido en el<NEXT>interior de la",
    ["text2"] = "tierra, y por eso<NEXT>es hasta más duro<NEXT>que el diamante.",
  },
  ["PICHU"] = {
    ["text"] = "Todavía no domina<NEXT>el almacenamiento<NEXT>de electricidad, y",
    ["text2"] = "descargará un<NEXT>rayo si se<NEXT>divierte o asusta.",
  },
  ["VENOMOTH"] = {
    ["text"] = "Cuando ataca,<NEXT>agita sus largas<NEXT>alas violentamente",
    ["text2"] = "para esparcir<NEXT>polvo venenoso<NEXT>a su alrededor.",
  },
  ["RAICHU"] = {
    ["text"] = "Cuando se carga de<NEXT>electricidad, sus<NEXT>músculos se tensan",
    ["text2"] = "y se vuelve más<NEXT>agresivo de lo<NEXT>normal.",
  },
  ["SHELLDER"] = {
    ["text"] = "Nada hacia atrás<NEXT>abriendo y<NEXT>cerrando su",
    ["text2"] = "concha. Es<NEXT>sorprendentemente<NEXT>rápido.",
  },
  ["ZUBAT"] = {
    ["text"] = "Al volar, emite<NEXT>constantemente<NEXT>ondas ultrasónicas",
    ["text2"] = "por la boca para<NEXT>comprobar los<NEXT>alrededores.",
  },
  ["SUNFLORA"] = {
    ["text"] = "Convierte la luz<NEXT>solar en energía.<NEXT>En la oscuridad,",
    ["text2"] = "tras el atardecer,<NEXT>cierra sus pétalos<NEXT>y queda inmóvil.",
  },
  ["MILTANK"] = {
    ["text"] = "Su leche, rica en<NEXT>nutrientes, es la<NEXT>mejor bebida",
    ["text2"] = "contra el<NEXT>cansancio y<NEXT>la enfermedad.",
  },
  ["QUILAVA"] = {
    ["text"] = "Ten cuidado si<NEXT>te da la espalda<NEXT>en combate.",
    ["text2"] = "Significa que te<NEXT>va a atacar con<NEXT>su lomo de fuego.",
  },
  ["SEADRA"] = {
    ["text"] = "Un análisis de sus<NEXT>células revela la<NEXT>presencia de un",
    ["text2"] = "gen no encontrado<NEXT>en HORSEA. Es un<NEXT>tema muy polémico.",
  },
  ["GEODUDE"] = {
    ["text"] = "Puede que mucha<NEXT>gente no se dé<NEXT>cuenta, pero si lo",
    ["text2"] = "miras de cerca,<NEXT>descubrirás muchos<NEXT>GEODUDE alrededor.",
  },
  ["TOGEPI"] = {
    ["text"] = "El cascarón parece<NEXT>estar lleno de<NEXT>alegría. Dicen que",
    ["text2"] = "trae buena suerte<NEXT>si es tratado<NEXT>con cariño.",
  },
  ["MEGANIUM"] = {
    ["text"] = "El olor que<NEXT>desprenden sus<NEXT>pétalos contiene",
    ["text2"] = "una sustancia que<NEXT>calma el instinto<NEXT>agresivo.",
  },
  ["UMBREON"] = {
    ["text"] = "Cuando se siente<NEXT>amenazado, este<NEXT>POKéMON se protege",
    ["text2"] = "lanzando sudor<NEXT>venenoso por<NEXT>todos sus poros.",
  },
  ["POLIWAG"] = {
    ["text"] = "Por ser un poco<NEXT>torpe al caminar<NEXT>con sus jóvenes",
    ["text2"] = "patas, siempre<NEXT>prefiere nadar<NEXT>a caminar.",
  },
  ["SCIZOR"] = {
    ["text"] = "Mueve sus pinzas<NEXT>para asustar al<NEXT>enemigo. Por los",
    ["text2"] = "dibujos de su<NEXT>cuerpo parece<NEXT>tener 3 cabezas.",
  },
  ["EXEGGUTOR"] = {
    ["text"] = "Sus tres cabezas<NEXT>piensan de forma<NEXT>independiente.",
    ["text2"] = "Sin embargo, son<NEXT>amigas y no suelen<NEXT>discutir nunca.",
  },
  ["ALAKAZAM"] = {
    ["text"] = "Cerrando sus ojos<NEXT>aumenta sus demás<NEXT>sentidos. Esto le",
    ["text2"] = "permite usar<NEXT>sus habilidades<NEXT>al máximo.",
  },
  ["MOLTRES"] = {
    ["text"] = "Este POKéMON<NEXT>legendario esparce<NEXT>ascuas con cada",
    ["text2"] = "aleteo. Es una<NEXT>visión digna<NEXT>de ver.",
  },
  ["TOTODILE"] = {
    ["text"] = "Sus desarrolladas<NEXT>y potentes fauces<NEXT>pueden romper",
    ["text2"] = "cualquier cosa. Su<NEXT>entrenador debe<NEXT>tener cuidado.",
  },
  ["PORYGON"] = {
    ["text"] = "Es un POKéMON<NEXT>creado por el<NEXT>hombre. Como no",
    ["text2"] = "respira, la gente<NEXT>quiere probarlo en<NEXT>cualquier sitio.",
  },
  ["WEEDLE"] = {
    ["text"] = "Su venenoso<NEXT>aguijón es muy<NEXT>potente, y su",
    ["text2"] = "colorido cuerpo<NEXT>hace que los<NEXT>enemigos huyan.",
  },
  ["QWILFISH"] = {
    ["text"] = "Para arrojar sus<NEXT>venenosas púas,<NEXT>infla su cuerpo",
    ["text2"] = "bebiendo hasta<NEXT>10 litros de agua<NEXT>de una sola vez.",
  },
  ["METAPOD"] = {
    ["text"] = "En el caparazón,<NEXT>mientras se<NEXT>prepara para",
    ["text2"] = "evolucionar, está<NEXT>blando y débil, en<NEXT>estado catatónico.",
  },
  ["GOLEM"] = {
    ["text"] = "Muda su piel una<NEXT>vez al año. La<NEXT>concha desechada",
    ["text2"] = "se endurece de<NEXT>inmediato y se<NEXT>desmorona.",
  },
  ["SMEARGLE"] = {
    ["text"] = "La punta de su<NEXT>cola rezuma un<NEXT>fluido especial.",
    ["text2"] = "Lo pinta todo con<NEXT>este líquido para<NEXT>marcar su terreno.",
  },
  ["DODRIO"] = {
    ["text"] = "Recoge datos y<NEXT>hace planes el<NEXT>triple de rápido,",
    ["text2"] = "pero si piensa<NEXT>demasiado podría<NEXT>quedar paralizado.",
  },
  ["REMORAID"] = {
    ["text"] = "Tiene muy buena<NEXT>puntería. Dispara<NEXT>agua a sus presas,",
    ["text2"] = "hasta si se están<NEXT>moviendo, a más<NEXT>de 100 metros.",
  },
  ["CORSOLA"] = {
    ["text"] = "Crece y muda<NEXT>continuamente.<NEXT>La parte superior",
    ["text2"] = "de su cabeza es<NEXT>muy apreciada<NEXT>por su belleza.",
  },
  ["SMOOCHUM"] = {
    ["text"] = "Sus labios son la<NEXT>parte más sensible<NEXT>de su cuerpo.",
    ["text2"] = "Siempre los usa<NEXT>para examinar<NEXT>las cosas.",
  },
  ["QUAGSIRE"] = {
    ["text"] = "Este despreocupado<NEXT>POKéMON es de<NEXT>naturaleza",
    ["text2"] = "tranquila. Siempre<NEXT>que nada, choca<NEXT>con los barcos.",
  },
  ["SQUIRTLE"] = {
    ["text"] = "Su caparazón es<NEXT>blando al nacer.<NEXT>Pero pronto se",
    ["text2"] = "endurecerá y será<NEXT>capaz de resistir<NEXT>cualquier amenaza.",
  },
  ["OCTILLERY"] = {
    ["text"] = "Atrapa a los<NEXT>enemigos con<NEXT>sus tentáculos,",
    ["text2"] = "y después los<NEXT>golpea con su<NEXT>dura cabeza.",
  },
  ["JUMPLUFF"] = {
    ["text"] = "Si es llevado por<NEXT>el viento, podría<NEXT>dar la vuelta al",
    ["text2"] = "mundo controlando<NEXT>el vuelo con sus<NEXT>esporas.",
  },
  ["CLEFFA"] = {
    ["text"] = "Por su inusual<NEXT>forma estrellada,<NEXT>la gente cree que",
    ["text2"] = "procede de un<NEXT>meteorito que<NEXT>cayó a la tierra.",
  },
  ["SPEAROW"] = {
    ["text"] = "Aletea con sus<NEXT>cortas alas para<NEXT>hacer salir a los",
    ["text2"] = "insectos de la<NEXT>hierba, y los<NEXT>caza con su pico.",
  },
  ["KANGASKHAN"] = {
    ["text"] = "Si no hay peligro,<NEXT>el joven sale de<NEXT>la bolsa y juega.",
    ["text2"] = "El adulto vigila<NEXT>atentamente<NEXT>al joven.",
  },
  ["AERODACTYL"] = {
    ["text"] = "Un malvado POKéMON<NEXT>que data de hace<NEXT>mucho tiempo.",
    ["text2"] = "Parece volar<NEXT>extendiendo sus<NEXT>alas y planeando.",
  },
  ["SANDSHREW"] = {
    ["text"] = "Si cae de gran<NEXT>altura, este<NEXT>POKéMON podría",
    ["text2"] = "convertirse en una<NEXT>pelota y rebotar<NEXT>contra el suelo.",
  },
  ["CELEBI"] = {
    ["text"] = "Este POKéMON vaga<NEXT>por el tiempo. La<NEXT>hierba y los",
    ["text2"] = "árboles crecen<NEXT>por los campos<NEXT>por donde pasa.",
  },
  ["TANGELA"] = {
    ["text"] = "Las cintas que<NEXT>ocultan todo su<NEXT>cuerpo no dejan de",
    ["text2"] = "moverse. Esto<NEXT>desconcierta a<NEXT>sus enemigos.",
  },
  ["ARBOK"] = {
    ["text"] = "Paralizando a su<NEXT>presa con los<NEXT>dibujos de su",
    ["text2"] = "piel, apresa y<NEXT>envenena a la<NEXT>asustada víctima.",
  },
  ["SNUBBULL"] = {
    ["text"] = "Aunque parezca<NEXT>aterrador, en<NEXT>realidad es amable",
    ["text2"] = "y afectuoso. Es<NEXT>muy popular entre<NEXT>las mujeres.",
  },
  ["VICTREEBEL"] = {
    ["text"] = "El ÁCIDO con que<NEXT>disuelve a muchas<NEXT>presas se endulza,",
    ["text2"] = "haciéndolo hasta<NEXT>más efectivo para<NEXT>atraer a su presa.",
  },
  ["GLIGAR"] = {
    ["text"] = "Vuela directo a la<NEXT>cara del objetivo,<NEXT>y acaba con su",
    ["text2"] = "aterrada víctima<NEXT>inyectándole<NEXT>veneno.",
  },
  ["VULPIX"] = {
    ["text"] = "A medida que<NEXT>crece, su blanca<NEXT>cola gana color",
    ["text2"] = "y se divide en<NEXT>seis. Es cálido<NEXT>y adorable.",
  },
  ["HITMONLEE"] = {
    ["text"] = "Este POKéMON<NEXT>tiene un sentido<NEXT>del equilibrio",
    ["text2"] = "increíble. Puede<NEXT>dar patadas desde<NEXT>cualquier sitio.",
  },
  ["KINGLER"] = {
    ["text"] = "Le cuesta levantar<NEXT>su exagerada y<NEXT>desproporcionada",
    ["text2"] = "pinza. Su tamaño<NEXT>le impide apuntar<NEXT>correctamente.",
  },
  ["GOLBAT"] = {
    ["text"] = "Por muy dura que<NEXT>sea la piel de su<NEXT>víctima, clava sus",
    ["text2"] = "afilados colmillos<NEXT>para atiborrarse<NEXT>de su sangre.",
  },
  ["UNOWN"] = {
    ["text"] = "Tienen forma de<NEXT>jeroglíficos<NEXT>sobre lápidas",
    ["text2"] = "antiguas. Dicen<NEXT>que ambos están<NEXT>relacionados.",
  },
  ["VENUSAUR"] = {
    ["text"] = "Llena su cuerpo de<NEXT>energía con los<NEXT>rayos solares que",
    ["text2"] = "captan los anchos<NEXT>pétalos de su<NEXT>flor.",
  },
  ["VILEPLUME"] = {
    ["text"] = "Tiene los pétalos<NEXT>más grandes del<NEXT>mundo. Éstos",
    ["text2"] = "expulsan densas<NEXT>nubes de polen<NEXT>tóxico al caminar.",
  },
  ["PILOSWINE"] = {
    ["text"] = "Como su largo<NEXT>vello corporal<NEXT>le impide ver con",
    ["text2"] = "claridad, sigue<NEXT>atacando<NEXT>repetidamente.",
  },
  ["MACHOP"] = {
    ["text"] = "Siempre rebosante<NEXT>de fuerza, pasa el<NEXT>tiempo levantando",
    ["text2"] = "piedras. Esto<NEXT>le lleva a ser<NEXT>aún más fuerte.",
  },
  ["LANTURN"] = {
    ["text"] = "La luz que emite<NEXT>es tan brillante<NEXT>que puede iluminar",
    ["text2"] = "la superficie del<NEXT>mar desde unos 5<NEXT>km de profundidad.",
  },
  ["YANMA"] = {
    ["text"] = "Si aletea muy<NEXT>rápido, genera<NEXT>ondas expansivas",
    ["text2"] = "capaces de hacer<NEXT>añicos todas las<NEXT>ventanas próximas.",
  },
  ["WOOPER"] = {
    ["text"] = "Este POKéMON vive<NEXT>en aguas frías.<NEXT>Sale del agua",
    ["text2"] = "para buscar comida<NEXT>cuando refresca<NEXT>el ambiente.",
  },
  ["CLEFABLE"] = {
    ["text"] = "Con su fino oído<NEXT>puede percibir<NEXT>sonidos muy",
    ["text2"] = "lejanos. Suele<NEXT>habitar en lugares<NEXT>silenciosos.",
  },
  ["SHUCKLE"] = {
    ["text"] = "Las BAYAS que<NEXT>almacena en su<NEXT>concha se",
    ["text2"] = "descomponen en<NEXT>un líquido<NEXT>pegajoso.",
  },
  ["CLOYSTER"] = {
    ["text"] = "Cuando cierra de<NEXT>golpe su concha<NEXT>será imposible",
    ["text2"] = "abrirla, hasta<NEXT>por los más<NEXT>fuertes.",
  },
  ["HOUNDOUR"] = {
    ["text"] = "Usa diferentes<NEXT>tipos de gritos<NEXT>para comunicarse",
    ["text2"] = "con los de su<NEXT>especie, o para<NEXT>seguir a su presa.",
  },
  ["KAKUNA"] = {
    ["text"] = "Aunque sea un<NEXT>capullo, es capaz<NEXT>de moverse.",
    ["text2"] = "Extenderá su púa<NEXT>venenosa si es<NEXT>atacado.",
  },
  ["NIDORINO"] = {
    ["text"] = "Levanta sus<NEXT>grandes orejas<NEXT>para vigilar.",
    ["text2"] = "Si detecta algo,<NEXT>atacará de<NEXT>inmediato.",
  },
  ["MACHOKE"] = {
    ["text"] = "Siempre va a<NEXT>máxima potencia,<NEXT>pero este fuerte",
    ["text2"] = "y resistente<NEXT>POKéMON no se<NEXT>cansa nunca.",
  },
  ["DUGTRIO"] = {
    ["text"] = "Sus tres cabezas<NEXT>suben y bajan<NEXT>para remover la",
    ["text2"] = "tierra cercana,<NEXT>facilitándole<NEXT>la excavación.",
  },
  ["SWINUB"] = {
    ["text"] = "Frota su hocico<NEXT>contra el suelo<NEXT>para desenterrar",
    ["text2"] = "comida. A veces<NEXT>descubre aguas<NEXT>termales.",
  },
  ["MANTINE"] = {
    ["text"] = "Mientras nada<NEXT>majestuosamente,<NEXT>no le importa",
    ["text2"] = "que REMORAID le<NEXT>siga para comerse<NEXT>sus sobras.",
  },
  ["XATU"] = {
    ["text"] = "Dicen que se<NEXT>mantiene quieto<NEXT>y en silencio",
    ["text2"] = "porque observa el<NEXT>pasado y el futuro<NEXT>al mismo tiempo.",
  },
  ["LARVITAR"] = {
    ["text"] = "Se alimenta de<NEXT>tierra. Después<NEXT>de comer una gran",
    ["text2"] = "montaña, se duerme<NEXT>y empieza<NEXT>a crecer.",
  },
  ["AMPHAROS"] = {
    ["text"] = "La punta de su<NEXT>cola reluce<NEXT>brillantemente y",
    ["text2"] = "puede ser vista<NEXT>desde lejos. Es<NEXT>usado como faro.",
  },
  ["VENONAT"] = {
    ["text"] = "Sus ojos también<NEXT>funcionan como<NEXT>radares. Atrapa",
    ["text2"] = "y come pequeños<NEXT>bichos ocultos<NEXT>en la oscuridad.",
  },
  ["DROWZEE"] = {
    ["text"] = "Si crees haber<NEXT>tenido un buen<NEXT>sueño, y no puedes",
    ["text2"] = "acordarte, seguro<NEXT>que se lo ha<NEXT>comido un DROWZEE.",
  },
}
